services:
  postgres:
    container_name: gado_api_container
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=gado123
      - POSTGRES_DB=gado
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data  # Esto mapea un directorio local
